# -*- coding: utf-8 -*-
"""corrigirColunasFavorecidos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFx82fVYkKBc29V825jECEAsTT8B0hsK
"""


import pandas as pd

def split_month_year(df, column_name='Mês Ano'):
  """
  Splits a 'Mês Ano' column (e.g., 'jan/21') into separate 'Mês' and 'Ano' columns.

  Args:
    df: pandas DataFrame containing the 'Mês Ano' column.
    column_name: The name of the column to split.

  Returns:
    A new DataFrame with the added 'Mês' and 'Ano' columns.
    Returns the original DataFrame if the column is not found or if errors occur.
  """
  try:
    # Create month mapping
    month_mapping = {
        'jan': '01', 'fev': '02', 'mar': '03', 'abr': '04', 'mai': '05', 'jun': '06',
        'jul': '07', 'ago': '08', 'set': '09', 'out': '10', 'nov': '11', 'dez': '12'
    }

    # # Handle potential missing values or non-string values gracefully
    # df['Ano'] = df[column_name].astype(str).str.lower().str.split('4').str[0]
    # df['Mes'] = df[column_name].astype(str).str.split('4').str[1].map(month_mapping)
    #df[['Mes', 'Ano']] = df[column_name].str.split('/', n=1, expand=True)

    df[column_name] = df[column_name].astype(str)    
    df['Ano'] = df[column_name].str.slice(0, 4)  # Os primeiros 4 caracteres correspondem ao ano
    df['Mes'] = df[column_name].str.slice(4, 6)  # Os próximos 2 caracteres correspondem ao mês

    df['Ano'] = df['Ano'].astype(int)
    df['Mes'] = df['Mes'].astype(int)

    return df

  except KeyError:
    print(f"Error: Column '{column_name}' not found in DataFrame.")
    return df
  except Exception as e:
    print(f"An error occurred: {e}")
    return df

def split_cnpj_nome(df, column_name='Favorecido'):
    # Split using str.split with expand=True to capture in 2 columns
    # Check if the column_name exists before attempting to split
    if column_name in df.columns:
        df[['Código Favorecido', 'Nome Favorecido']] = df[column_name].str.split(' - ', n=1, expand=True)
    else:
        print(f"Error: Column '{column_name}' not found in DataFrame.")

    return df



# Read the CSV with the correct delimiter and quotechar
df = pd.read_csv('resultados/2021recursosrecebidos.csv', on_bad_lines='skip', sep=',', quotechar='"')
print(df.columns)

# Now call the functions with the corrected column names
#split_cnpj_nome(df, column_name='Favorecido')
split_month_year(df, column_name='anoMes')

df= df.drop(columns=['anoMes'])
print(df.columns)
df.to_csv('favorecidos2021.csv', index=False)

